- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "cmd_vel"
  gz_topic_name: "cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

# - ros_topic_name: "/touch_sensor/touched"
#   gz_topic_name: "/touch_sensor/touched"
#   ros_type_name: "std_msgs/msg/Bool"
#   gz_type_name: "gz.msgs.Boolean"
#   direction: BIDIRECTIONAL
# Full set of configurations
# - ros_topic_name: "ros_chatter"
#   gz_topic_name: "gz_chatter"
#   ros_type_name: "std_msgs/msg/String"
#   gz_type_name: "gz.msgs.StringMsg"
#   subscriber_queue: 10       # Default 10
#   publisher_queue: 10        # Default 10
#   lazy: false                # Default "false"
#   direction: BIDIRECTIONAL  # Default "BIDIRECTIONAL" - Bridge both directions
#                             # "GZ_TO_ROS" - Bridge Gz topic to ROS
#                             # "ROS_TO_GZ" - Bridge ROS topic to Gz