robots:
  ur5e:
    joint_state_topic: /ur5e/joint_states
    controllers:
      arm:
        action_name: /ur5e/ur5e_joint_trajectory_controller/follow_joint_trajectory
        action_type: follow_joint_trajectory
        joint_names:
        - ur5e_shoulder_pan_joint
        - ur5e_shoulder_lift_joint
        - ur5e_elbow_joint
        - ur5e_wrist_1_joint
        - ur5e_wrist_2_joint
        - ur5e_wrist_3_joint
        goal_tolerance_sec: 1.0
      gripper:
        action_name: /ur5e/onrobot_gripper_controller/gripper_cmd
        action_type: gripper_command
        joint_names:
          - ur5e_onrobot_gripper_joint
        max_effort: 40.0
    tasks:
      HOME:
        task_name: home
        steps:
          - name: open_gripper
            controller: gripper
            positions: [0.0]
            duration: 1.0
          - name: move_home
            controller: arm
            positions: [0.0, -1.57, 0.0, -1.57, 0.0, 0.0]
            duration: 4.0
      START_PICK_AND_PLACE_TO_HANDOVER:
        task_name: pick_and_place_to_handover
        steps:
          - name: approach_pick
            controller: arm
            positions: [-0.14, -1.31, 1.2917, -1.502, -1.3430, 1.154]
            duration: 4.0
          - name: open_gripper
            controller: gripper
            positions: [0.0]
            duration: 1.0
          - name: descend_to_pick
            controller: arm
            positions: [1.42311, -2.0942, 1.2917, -1.5024, -1.3430, 1.1543]
            duration: 4.0
          - name: open_gripper
            controller: gripper
            positions: [0.0]
            duration: 1.0
          - name: lift_and_move_to_handover
            controller: arm
            positions: [2.7925, -2.0942, 1.2917, -1.5024, -1.3430, 1.1543]
            duration: 3.0
          - name: release_to_handover
            controller: gripper
            positions: [0.08]
            duration: 1.0
  kuka:
    joint_state_topic: /kuka/joint_states
    controllers:
      arm:
        action_name: /kuka/kuka_arm_controller/follow_joint_trajectory
        action_type: follow_joint_trajectory
        joint_names:
          - kuka_joint_a1
          - kuka_joint_a2
          - kuka_joint_a3
          - kuka_joint_a4
          - kuka_joint_a5
          - kuka_joint_a6
        goal_tolerance_sec: 1.0
      gripper:
        action_name: /kuka/kuka_gripper_controller/follow_joint_trajectory
        action_type: follow_joint_trajectory
        joint_names:
          - kuka_egp64_finger_left_joint
          - kuka_egp64_finger_right_joint
        goal_tolerance_sec: 1.0
    tasks:
      HOME:
        task_name: home
        steps:
          - name: open_gripper
            controller: gripper
            positions: [0.02, 0.02]
            duration: 1.0
          - name: move_home
            controller: arm
            positions: [-1.0, -1.0, 0.9, 0.0, 0.0, 0.0]
            duration: 4.0
      START_PICK_AND_SORT:
        task_name: pick_and_sort
        steps:
          - name: approach_handover
            controller: arm
            positions: [-0.35, -1.25, 1.55, 0.10, 0.60, -0.35]
            duration: 4.0
          - name: open_gripper
            controller: gripper
            positions: [0.02, 0.02]
            duration: 1.0
          - name: receive_from_handover
            controller: arm
            positions: [-1.003, -1.000, 1.1000, 0.0008, 0.4999, -0.0001]
            duration: 4.0
          - name: close_gripper
            controller: gripper
            positions: [0.0, 0.0]
            duration: 1.0
          - name: move_to_sort_bin
            controller: arm
            positions: [-1.3918, -0.949, 1.3260, 0.0004, 0.4999, 0.00009]
            duration: 4.0
          - name: release_to_sort_bin
            controller: gripper
            positions: [0.02, 0.02]
            duration: 1.0
          - name: retreat_from_sort_bin
            controller: arm
            positions: [-2.2872, -0.4538, 0.9728, 0.3466, 0.9899, -0.5596]
            duration: 2.0

